#!/usr/bin/env php
<?php
declare(ticks=1);

use Ballen\Clip\Utilities\CommandRouter;
use Ballen\Clip\Exceptions\CommandNotFoundException;
use Ballen\Pirrot\Commands\IdentCommand;
use Ballen\Pirrot\Commands\VoiceCommand;
use Ballen\Pirrot\Commands\UpdateCommand;
use Ballen\Pirrot\Commands\HelpCommand;
use Ballen\Pirrot\Commands\TerminateCommand;

// Set the current directory of the CLI script.
$bindir = dirname(__FILE__);

//require_once $bindir . '/app/Helpers/ProcessHandler.php';

// Initiate the Composer autoloader.
require_once $bindir . '/vendor/autoload.php';

$app = new CommandRouter($argv);

// Add our commands and their handler class mappings
$app->add('ident', IdentCommand::class);
$app->add('voice', VoiceCommand::class);
$app->add('update', UpdateCommand::class);
$app->add('help', HelpCommand::class);
$app->add('cleanup', TerminateCommand::class);

// Register process signal handlers
foreach ([SIGINT, SIGTERM] as $signalType) {
    pcntl_signal($signalType, function ($signal) use ($app) {
        $app->dispatch('terminate');
    });
}

// Boot the application/daemon
try {
    $app->dispatch();
} catch (CommandNotFoundException $exception) {
    $app->dispatch('help');
}