#!/usr/bin/env php
<?php
use Ballen\Clip\Utilities\CommandRouter;
use Ballen\Clip\Exceptions\CommandNotFoundException;
use Ballen\Pirrot\Commands\IdentCommand;
use Ballen\Pirrot\Commands\VoiceCommand;
use Ballen\Pirrot\Commands\UpdateCommand;
use Ballen\Pirrot\Commands\HelpCommand;
// Test classes...
use Ballen\Pirrot\Commands\IoCommand;
use Ballen\Pirrot\Commands\IoInteruptCommand;

// Set the current directory of the CLI script.
$bindir = dirname(__FILE__);

// Initiate the Composer autoloader.
require_once $bindir . '/vendor/autoload.php';

$app = new CommandRouter($argv);

// Add our commands and their handler class mappings
$app->add('ident', IdentCommand::class);
$app->add('voice', VoiceCommand::class);
$app->add('update', UpdateCommand::class);
$app->add('help', HelpCommand::class);

// Test commands - will be removed in future!!
$app->add('io', IoCommand::class);
$app->add('ioi', IoInteruptCommand::class);

try {
    $app->dispatch();
} catch (CommandNotFoundException $exception) {
    // If the requested command is not found we'll display the 'help' text by default?
    $app->dispatch('help');
}